//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRP_Invoice.publishwebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="publishwebservice.PublishServiceSoap")]
    public interface PublishServiceSoap {
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportAndPublishInv", ReplyAction="*")]
        CRP_Invoice.publishwebservice.ImportAndPublishInvResponse ImportAndPublishInv(CRP_Invoice.publishwebservice.ImportAndPublishInvRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvPattern", ReplyAction="*")]
        CRP_Invoice.publishwebservice.ImportInvPatternResponse ImportInvPattern(CRP_Invoice.publishwebservice.ImportInvPatternRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInv", ReplyAction="*")]
        CRP_Invoice.publishwebservice.ImportInvResponse ImportInv(CRP_Invoice.publishwebservice.ImportInvRequest request);
        
        // CODEGEN: Generating message contract since element name invIDs from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInv", ReplyAction="*")]
        CRP_Invoice.publishwebservice.publishInvResponse publishInv(CRP_Invoice.publishwebservice.publishInvRequest request);
        
        // CODEGEN: Generating message contract since element name XMLCusData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCus", ReplyAction="*")]
        CRP_Invoice.publishwebservice.UpdateCusResponse UpdateCus(CRP_Invoice.publishwebservice.UpdateCusRequest request);
        
        // CODEGEN: Generating message contract since element name certSerial from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setCusCert", ReplyAction="*")]
        CRP_Invoice.publishwebservice.setCusCertResponse setCusCert(CRP_Invoice.publishwebservice.setCusCertRequest request);
        
        // CODEGEN: Generating message contract since element name xmlInvData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportInvByPatternSerial", ReplyAction="*")]
        CRP_Invoice.publishwebservice.ImportInvByPatternSerialResponse ImportInvByPatternSerial(CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequest request);
        
        // CODEGEN: Generating message contract since element name Account from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publishInvFkey", ReplyAction="*")]
        CRP_Invoice.publishwebservice.publishInvFkeyResponse publishInvFkey(CRP_Invoice.publishwebservice.publishInvFkeyRequest request);
        
        // CODEGEN: Generating message contract since element name lsFkey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteInvFkey", ReplyAction="*")]
        CRP_Invoice.publishwebservice.deleteInvFkeyResponse deleteInvFkey(CRP_Invoice.publishwebservice.deleteInvFkeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInv", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportAndPublishInvRequestBody Body;
        
        public ImportAndPublishInvRequest() {
        }
        
        public ImportAndPublishInvRequest(CRP_Invoice.publishwebservice.ImportAndPublishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int convert;
        
        public ImportAndPublishInvRequestBody() {
        }
        
        public ImportAndPublishInvRequestBody(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportAndPublishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportAndPublishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportAndPublishInvResponseBody Body;
        
        public ImportAndPublishInvResponse() {
        }
        
        public ImportAndPublishInvResponse(CRP_Invoice.publishwebservice.ImportAndPublishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportAndPublishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportAndPublishInvResult;
        
        public ImportAndPublishInvResponseBody() {
        }
        
        public ImportAndPublishInvResponseBody(string ImportAndPublishInvResult) {
            this.ImportAndPublishInvResult = ImportAndPublishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPattern", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvPatternRequestBody Body;
        
        public ImportInvPatternRequest() {
        }
        
        public ImportInvPatternRequest(CRP_Invoice.publishwebservice.ImportInvPatternRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string serial;
        
        public ImportInvPatternRequestBody() {
        }
        
        public ImportInvPatternRequestBody(string xmlInvData, string username, string password, int convert, string pattern, string serial) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvPatternResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvPatternResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvPatternResponseBody Body;
        
        public ImportInvPatternResponse() {
        }
        
        public ImportInvPatternResponse(CRP_Invoice.publishwebservice.ImportInvPatternResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvPatternResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvPatternResult;
        
        public ImportInvPatternResponseBody() {
        }
        
        public ImportInvPatternResponseBody(string ImportInvPatternResult) {
            this.ImportInvPatternResult = ImportInvPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInv", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvRequestBody Body;
        
        public ImportInvRequest() {
        }
        
        public ImportInvRequest(CRP_Invoice.publishwebservice.ImportInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int convert;
        
        public ImportInvRequestBody() {
        }
        
        public ImportInvRequestBody(string xmlInvData, string username, string password, int convert) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.password = password;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvResponseBody Body;
        
        public ImportInvResponse() {
        }
        
        public ImportInvResponse(CRP_Invoice.publishwebservice.ImportInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvResult;
        
        public ImportInvResponseBody() {
        }
        
        public ImportInvResponseBody(string ImportInvResult) {
            this.ImportInvResult = ImportInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInv", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.publishInvRequestBody Body;
        
        public publishInvRequest() {
        }
        
        public publishInvRequest(CRP_Invoice.publishwebservice.publishInvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRP_Invoice.publishwebservice.ArrayOfInt invIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        public publishInvRequestBody() {
        }
        
        public publishInvRequestBody(CRP_Invoice.publishwebservice.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            this.invIDs = invIDs;
            this.username = username;
            this.password = password;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.publishInvResponseBody Body;
        
        public publishInvResponse() {
        }
        
        public publishInvResponse(CRP_Invoice.publishwebservice.publishInvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvResult;
        
        public publishInvResponseBody() {
        }
        
        public publishInvResponseBody(string publishInvResult) {
            this.publishInvResult = publishInvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCus", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.UpdateCusRequestBody Body;
        
        public UpdateCusRequest() {
        }
        
        public UpdateCusRequest(CRP_Invoice.publishwebservice.UpdateCusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XMLCusData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> convert;
        
        public UpdateCusRequestBody() {
        }
        
        public UpdateCusRequestBody(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            this.XMLCusData = XMLCusData;
            this.username = username;
            this.pass = pass;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCusResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.UpdateCusResponseBody Body;
        
        public UpdateCusResponse() {
        }
        
        public UpdateCusResponse(CRP_Invoice.publishwebservice.UpdateCusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateCusResult;
        
        public UpdateCusResponseBody() {
        }
        
        public UpdateCusResponseBody(int UpdateCusResult) {
            this.UpdateCusResult = UpdateCusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCert", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.setCusCertRequestBody Body;
        
        public setCusCertRequest() {
        }
        
        public setCusCertRequest(CRP_Invoice.publishwebservice.setCusCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string certSerial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string certString;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cusCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public setCusCertRequestBody() {
        }
        
        public setCusCertRequestBody(string certSerial, string certString, string cusCode, string username, string pass) {
            this.certSerial = certSerial;
            this.certString = certString;
            this.cusCode = cusCode;
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCusCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCusCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.setCusCertResponseBody Body;
        
        public setCusCertResponse() {
        }
        
        public setCusCertResponse(CRP_Invoice.publishwebservice.setCusCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setCusCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int setCusCertResult;
        
        public setCusCertResponseBody() {
        }
        
        public setCusCertResponseBody(int setCusCertResult) {
            this.setCusCertResult = setCusCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerial", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequestBody Body;
        
        public ImportInvByPatternSerialRequest() {
        }
        
        public ImportInvByPatternSerialRequest(CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlInvData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int convert;
        
        public ImportInvByPatternSerialRequestBody() {
        }
        
        public ImportInvByPatternSerialRequestBody(string xmlInvData, string username, string pass, string pattern, string serial, int convert) {
            this.xmlInvData = xmlInvData;
            this.username = username;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
            this.convert = convert;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportInvByPatternSerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportInvByPatternSerialResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.ImportInvByPatternSerialResponseBody Body;
        
        public ImportInvByPatternSerialResponse() {
        }
        
        public ImportInvByPatternSerialResponse(CRP_Invoice.publishwebservice.ImportInvByPatternSerialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportInvByPatternSerialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ImportInvByPatternSerialResult;
        
        public ImportInvByPatternSerialResponseBody() {
        }
        
        public ImportInvByPatternSerialResponseBody(string ImportInvByPatternSerialResult) {
            this.ImportInvByPatternSerialResult = ImportInvByPatternSerialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.publishInvFkeyRequestBody Body;
        
        public publishInvFkeyRequest() {
        }
        
        public publishInvFkeyRequest(CRP_Invoice.publishwebservice.publishInvFkeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string serial;
        
        public publishInvFkeyRequestBody() {
        }
        
        public publishInvFkeyRequestBody(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial) {
            this.Account = Account;
            this.ACpass = ACpass;
            this.lsFkey = lsFkey;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
            this.serial = serial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publishInvFkeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publishInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.publishInvFkeyResponseBody Body;
        
        public publishInvFkeyResponse() {
        }
        
        public publishInvFkeyResponse(CRP_Invoice.publishwebservice.publishInvFkeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publishInvFkeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publishInvFkeyResult;
        
        public publishInvFkeyResponseBody() {
        }
        
        public publishInvFkeyResponseBody(string publishInvFkeyResult) {
            this.publishInvFkeyResult = publishInvFkeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkey", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.deleteInvFkeyRequestBody Body;
        
        public deleteInvFkeyRequest() {
        }
        
        public deleteInvFkeyRequest(CRP_Invoice.publishwebservice.deleteInvFkeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lsFkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ACpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pattern;
        
        public deleteInvFkeyRequestBody() {
        }
        
        public deleteInvFkeyRequestBody(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern) {
            this.lsFkey = lsFkey;
            this.Account = Account;
            this.ACpass = ACpass;
            this.userName = userName;
            this.pass = pass;
            this.pattern = pattern;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteInvFkeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteInvFkeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRP_Invoice.publishwebservice.deleteInvFkeyResponseBody Body;
        
        public deleteInvFkeyResponse() {
        }
        
        public deleteInvFkeyResponse(CRP_Invoice.publishwebservice.deleteInvFkeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteInvFkeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteInvFkeyResult;
        
        public deleteInvFkeyResponseBody() {
        }
        
        public deleteInvFkeyResponseBody(string deleteInvFkeyResult) {
            this.deleteInvFkeyResult = deleteInvFkeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PublishServiceSoapChannel : CRP_Invoice.publishwebservice.PublishServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublishServiceSoapClient : System.ServiceModel.ClientBase<CRP_Invoice.publishwebservice.PublishServiceSoap>, CRP_Invoice.publishwebservice.PublishServiceSoap {
        
        public PublishServiceSoapClient() {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublishServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.ImportAndPublishInvResponse CRP_Invoice.publishwebservice.PublishServiceSoap.ImportAndPublishInv(CRP_Invoice.publishwebservice.ImportAndPublishInvRequest request) {
            return base.Channel.ImportAndPublishInv(request);
        }
        
        public string ImportAndPublishInv(string Account, string ACpass, string xmlInvData, string username, string password, string pattern, string serial, int convert) {
            CRP_Invoice.publishwebservice.ImportAndPublishInvRequest inValue = new CRP_Invoice.publishwebservice.ImportAndPublishInvRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.ImportAndPublishInvRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            CRP_Invoice.publishwebservice.ImportAndPublishInvResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).ImportAndPublishInv(inValue);
            return retVal.Body.ImportAndPublishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.ImportInvPatternResponse CRP_Invoice.publishwebservice.PublishServiceSoap.ImportInvPattern(CRP_Invoice.publishwebservice.ImportInvPatternRequest request) {
            return base.Channel.ImportInvPattern(request);
        }
        
        public string ImportInvPattern(string xmlInvData, string username, string password, int convert, string pattern, string serial) {
            CRP_Invoice.publishwebservice.ImportInvPatternRequest inValue = new CRP_Invoice.publishwebservice.ImportInvPatternRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.ImportInvPatternRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            CRP_Invoice.publishwebservice.ImportInvPatternResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).ImportInvPattern(inValue);
            return retVal.Body.ImportInvPatternResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.ImportInvResponse CRP_Invoice.publishwebservice.PublishServiceSoap.ImportInv(CRP_Invoice.publishwebservice.ImportInvRequest request) {
            return base.Channel.ImportInv(request);
        }
        
        public string ImportInv(string xmlInvData, string username, string password, int convert) {
            CRP_Invoice.publishwebservice.ImportInvRequest inValue = new CRP_Invoice.publishwebservice.ImportInvRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.ImportInvRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.convert = convert;
            CRP_Invoice.publishwebservice.ImportInvResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).ImportInv(inValue);
            return retVal.Body.ImportInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.publishInvResponse CRP_Invoice.publishwebservice.PublishServiceSoap.publishInv(CRP_Invoice.publishwebservice.publishInvRequest request) {
            return base.Channel.publishInv(request);
        }
        
        public string publishInv(CRP_Invoice.publishwebservice.ArrayOfInt invIDs, string username, string password, string pattern, string serial) {
            CRP_Invoice.publishwebservice.publishInvRequest inValue = new CRP_Invoice.publishwebservice.publishInvRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.publishInvRequestBody();
            inValue.Body.invIDs = invIDs;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            CRP_Invoice.publishwebservice.publishInvResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).publishInv(inValue);
            return retVal.Body.publishInvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.UpdateCusResponse CRP_Invoice.publishwebservice.PublishServiceSoap.UpdateCus(CRP_Invoice.publishwebservice.UpdateCusRequest request) {
            return base.Channel.UpdateCus(request);
        }
        
        public int UpdateCus(string XMLCusData, string username, string pass, System.Nullable<int> convert) {
            CRP_Invoice.publishwebservice.UpdateCusRequest inValue = new CRP_Invoice.publishwebservice.UpdateCusRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.UpdateCusRequestBody();
            inValue.Body.XMLCusData = XMLCusData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.convert = convert;
            CRP_Invoice.publishwebservice.UpdateCusResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).UpdateCus(inValue);
            return retVal.Body.UpdateCusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.setCusCertResponse CRP_Invoice.publishwebservice.PublishServiceSoap.setCusCert(CRP_Invoice.publishwebservice.setCusCertRequest request) {
            return base.Channel.setCusCert(request);
        }
        
        public int setCusCert(string certSerial, string certString, string cusCode, string username, string pass) {
            CRP_Invoice.publishwebservice.setCusCertRequest inValue = new CRP_Invoice.publishwebservice.setCusCertRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.setCusCertRequestBody();
            inValue.Body.certSerial = certSerial;
            inValue.Body.certString = certString;
            inValue.Body.cusCode = cusCode;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            CRP_Invoice.publishwebservice.setCusCertResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).setCusCert(inValue);
            return retVal.Body.setCusCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.ImportInvByPatternSerialResponse CRP_Invoice.publishwebservice.PublishServiceSoap.ImportInvByPatternSerial(CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequest request) {
            return base.Channel.ImportInvByPatternSerial(request);
        }
        
        public string ImportInvByPatternSerial(string xmlInvData, string username, string pass, string pattern, string serial, int convert) {
            CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequest inValue = new CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.ImportInvByPatternSerialRequestBody();
            inValue.Body.xmlInvData = xmlInvData;
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            inValue.Body.convert = convert;
            CRP_Invoice.publishwebservice.ImportInvByPatternSerialResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).ImportInvByPatternSerial(inValue);
            return retVal.Body.ImportInvByPatternSerialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.publishInvFkeyResponse CRP_Invoice.publishwebservice.PublishServiceSoap.publishInvFkey(CRP_Invoice.publishwebservice.publishInvFkeyRequest request) {
            return base.Channel.publishInvFkey(request);
        }
        
        public string publishInvFkey(string Account, string ACpass, string lsFkey, string userName, string pass, string pattern, string serial) {
            CRP_Invoice.publishwebservice.publishInvFkeyRequest inValue = new CRP_Invoice.publishwebservice.publishInvFkeyRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.publishInvFkeyRequestBody();
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            inValue.Body.serial = serial;
            CRP_Invoice.publishwebservice.publishInvFkeyResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).publishInvFkey(inValue);
            return retVal.Body.publishInvFkeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRP_Invoice.publishwebservice.deleteInvFkeyResponse CRP_Invoice.publishwebservice.PublishServiceSoap.deleteInvFkey(CRP_Invoice.publishwebservice.deleteInvFkeyRequest request) {
            return base.Channel.deleteInvFkey(request);
        }
        
        public string deleteInvFkey(string lsFkey, string Account, string ACpass, string userName, string pass, string pattern) {
            CRP_Invoice.publishwebservice.deleteInvFkeyRequest inValue = new CRP_Invoice.publishwebservice.deleteInvFkeyRequest();
            inValue.Body = new CRP_Invoice.publishwebservice.deleteInvFkeyRequestBody();
            inValue.Body.lsFkey = lsFkey;
            inValue.Body.Account = Account;
            inValue.Body.ACpass = ACpass;
            inValue.Body.userName = userName;
            inValue.Body.pass = pass;
            inValue.Body.pattern = pattern;
            CRP_Invoice.publishwebservice.deleteInvFkeyResponse retVal = ((CRP_Invoice.publishwebservice.PublishServiceSoap)(this)).deleteInvFkey(inValue);
            return retVal.Body.deleteInvFkeyResult;
        }
    }
}
